# This is for PC Tool, transfer-hw-to-cert

name: Test transfer-hw-to-cert Tool

on:
  push:
    paths: ['Tools/PC/transfer-hw-to-cert/**']
  pull_request:
    paths: ['Tools/PC/transfer-hw-to-cert/**']

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test with unittest
      run: |
        python -m unittest -v